### ISSUE TITLE
seeds_generator.py give me 321485 files

### ISSUE THREAD

**Issue by Myskiper** [goodarzilab/pyteiser#1]
Hi goodarzilab,
     I saw your article, And we want to use pyteiser to test our RNAseq data. I installed it by conda.
     But when I run `python /pyteiser/seeds_generator.py --outfolder /ldfssz1/ST_CANCER/CGR/SHARE/tools/pyteiser --prefix human.hg38`, It's been running for eight hours, and get 321485 bins. Still running...
     Is that OK?

**Comment by khorms** [comment]
Hello,
1) You can change the --num_motifs_per_file parameter in order to balance the size of individual files vs number of files. I usually set it to 30000.
2) It takes long time to generate all the seeds with the default parameters, because the default parameters intentially represent a comprehensive set of seeds. You can limit the number of seeds covered by reducing the --max_loop_length and --max_stem_length parameters by 1-3
3) for convenience, I uploaded the default set of seed files that I use to Box ([link](https://ucsf.app.box.com/s/6rs6a4jbd2lxkj5fqjygg46xoh8aqbo7)), feel free to use them
I hope this helps

**Comment by Myskiper** [comment]
Thanks for your reply, I will try it with your seed files.
